# Generated by Django 2.2.5 on 2019-10-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kong_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_type',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
