# Generated by Django 2.2.5 on 2019-12-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kong_core', '0002_client_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user_type',
        ),
    ]
